package com.example.studenttracker;

import android.app.*;import android.os.*;import android.graphics.Color;import android.graphics.drawable.GradientDrawable;import android.database.Cursor;import android.view.*;import android.widget.*;import java.util.*;

public class MainActivity extends Activity{
 StudentDb db; LinearLayout root,content; String cls="1م أ"; int week=1,session=1,period=1;
 final int NAVY=Color.rgb(11,79,108),BLUE=Color.rgb(19,119,169),BG=Color.rgb(246,248,251),TEXT=Color.rgb(28,39,49),GREEN=Color.rgb(28,130,85),GOLD=Color.rgb(183,125,20);
 @Override public void onCreate(Bundle b){super.onCreate(b);getWindow().setStatusBarColor(NAVY);getWindow().getDecorView().setLayoutDirection(View.LAYOUT_DIRECTION_RTL);db=new StudentDb(this);home();}
 GradientDrawable shape(int c,int r){GradientDrawable g=new GradientDrawable();g.setColor(c);g.setCornerRadius(r);return g;}
 TextView text(String s,float z,boolean bold){TextView v=new TextView(this);v.setText(s);v.setTextSize(z);v.setTextColor(TEXT);v.setGravity(Gravity.RIGHT|Gravity.CENTER_VERTICAL);v.setTypeface(null,bold?1:0);v.setPadding(18,8,18,8);return v;}
 Button button(String s,boolean primary){Button b=new Button(this);b.setText(s);b.setAllCaps(false);b.setTextSize(13);b.setTextColor(primary?Color.WHITE:NAVY);b.setBackground(shape(primary?BLUE:Color.WHITE,22));return b;}
 void base(String title,String sub){root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(BG);LinearLayout head=new LinearLayout(this);head.setOrientation(LinearLayout.VERTICAL);head.setPadding(18,10,18,8);head.setBackgroundColor(NAVY);TextView h=text(title,21,true);h.setTextColor(Color.WHITE);head.addView(h);TextView s=text(sub,12,false);s.setTextColor(Color.WHITE);head.addView(s);root.addView(head,new LinearLayout.LayoutParams(-1,78));ScrollView sv=new ScrollView(this);content=new LinearLayout(this);content.setOrientation(LinearLayout.VERTICAL);content.setPadding(14,12,14,84);sv.addView(content);root.addView(sv,new LinearLayout.LayoutParams(-1,0,1));setContentView(root);nav();}
 void nav(){LinearLayout n=new LinearLayout(this);n.setPadding(4,5,4,5);n.setBackgroundColor(Color.WHITE);String[] a={"الرئيسية","الطلاب","الحضور","الدرجات","التقارير"};for(String s:a){Button q=button(s,false);q.setTextSize(10);q.setOnClickListener(v->{if(s.equals("الرئيسية"))home();else if(s.equals("الطلاب"))students();else if(s.equals("الحضور"))attendance();else if(s.equals("الدرجات"))grades();else reports();});n.addView(q,new LinearLayout.LayoutParams(0,55,1));}root.addView(n,new LinearLayout.LayoutParams(-1,65));}
 TextView section(String s){TextView v=text(s,15,true);v.setPadding(4,16,4,8);return v;}
 LinearLayout card(String label,String value,int color){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(16,8,16,8);c.setBackground(shape(Color.WHITE,18));c.setElevation(2);TextView a=text(label,11,false);TextView b=text(value,19,true);b.setTextColor(color);c.addView(a);c.addView(b);return c;}
 void gap(){Space x=new Space(this);content.addView(x,new LinearLayout.LayoutParams(1,7));}
 void picker(){Spinner sp=new Spinner(this);sp.setBackground(shape(Color.WHITE,18));sp.setAdapter(new ArrayAdapter<String>(this,android.R.layout.simple_spinner_dropdown_item,StudentDb.CLASSES));sp.setSelection(Math.max(0,Arrays.asList(StudentDb.CLASSES).indexOf(cls)));final boolean[] ready={false};sp.postDelayed(()->ready[0]=true,250);sp.setOnItemSelectedListener(new AdapterView.OnItemSelectedListener(){public void onNothingSelected(AdapterView<?> a){}public void onItemSelected(AdapterView<?> a,View v,int p,long id){if(ready[0]&&!StudentDb.CLASSES[p].equals(cls)){cls=StudentDb.CLASSES[p];home();}}});content.addView(sp,new LinearLayout.LayoutParams(-1,56));}
 void home(){base("المهارات الرقمية","نظام متابعة الطلاب • 1447–1448هـ");content.addView(section("الفصل الدراسي"));picker();gap();LinearLayout r=new LinearLayout(this);r.addView(card("عدد الطلاب",""+db.count(cls),NAVY),new LinearLayout.LayoutParams(0,88,1));r.addView(card("الحضور المسجل",db.present(cls)+" / "+db.marked(cls),GREEN),new LinearLayout.LayoutParams(0,88,1));content.addView(r);gap();LinearLayout r2=new LinearLayout(this);r2.addView(card("متوسط الفترة الأولى",fmt(db.avg(cls,1))+" / 100",BLUE),new LinearLayout.LayoutParams(0,88,1));r2.addView(card("متوسط الفترة الثانية",fmt(db.avg(cls,2))+" / 100",GOLD),new LinearLayout.LayoutParams(0,88,1));content.addView(r2);content.addView(section("إجراءات سريعة"));quick("＋ إضافة طالب",v->addStudent());quick("✓ تسجيل الحضور",v->attendance());quick("▣ إدخال الدرجات",v->grades());quick("▤ التقارير والإحصائيات",v->reports());}
 void quick(String s,View.OnClickListener l){Button b=button(s,true);b.setOnClickListener(l);content.addView(b,new LinearLayout.LayoutParams(-1,54));gap();}
 void students(){base("الطلاب","إدارة طلاب الفصل • "+cls);Button add=button("＋ إضافة طالب جديد",true);add.setOnClickListener(v->addStudent());content.addView(add);gap();EditText search=new EditText(this);search.setHint("بحث بالاسم أو الرقم");search.setSingleLine(true);search.setBackground(shape(Color.WHITE,18));content.addView(search);gap();renderStudents("");search.addTextChangedListener(new android.text.TextWatcher(){public void beforeTextChanged(CharSequence s,int a,int c,int d){}public void onTextChanged(CharSequence s,int a,int b,int c){renderStudents(s.toString());}public void afterTextChanged(android.text.Editable e){}});}
 void renderStudents(String filter){while(content.getChildCount()>5)content.removeViewAt(5);Cursor c=db.students(cls);int shown=0;while(c.moveToNext()){long id=c.getLong(0);int no=c.getInt(1);String name=c.getString(2);if(!filter.isEmpty()&&!name.contains(filter)&&!String.valueOf(no).contains(filter))continue;Button r=button(no+" • "+name,false);r.setGravity(Gravity.RIGHT|Gravity.CENTER_VERTICAL);r.setOnClickListener(v->studentActions(id,name,no));content.addView(r,new LinearLayout.LayoutParams(-1,54));gap();shown++;}c.close();if(shown==0)content.addView(text("لا يوجد طلاب مطابقون. أضف الطلاب من الزر أعلاه.",14,false));}
 void studentActions(long id,String name,int no){String[] a={"تعديل بيانات الطالب","حذف الطالب"};new AlertDialog.Builder(this).setTitle(no+" • "+name).setItems(a,(d,w)->{if(w==0)editStudent(id,no,name);else new AlertDialog.Builder(this).setTitle("تأكيد الحذف").setMessage("سيتم حذف بيانات الطالب والحضور والدرجات.").setPositiveButton("حذف",(x,y)->{db.delete(id);students();}).setNegativeButton("إلغاء",null).show();}).show();}
 void addStudent(){editStudent(-1,0,"");}
 void editStudent(long id,int oldNo,String oldName){LinearLayout f=new LinearLayout(this);f.setOrientation(LinearLayout.VERTICAL);EditText no=new EditText(this);no.setHint("رقم الطالب");no.setInputType(2);no.setText(oldNo==0?"":String.valueOf(oldNo));EditText name=new EditText(this);name.setHint("اسم الطالب");name.setText(oldName);f.addView(no);f.addView(name);new AlertDialog.Builder(this).setTitle(id<0?"إضافة طالب":"تعديل الطالب").setView(f).setPositiveButton("حفظ",(d,w)->{try{int n=Integer.parseInt(no.getText().toString());String nm=name.getText().toString().trim();if(nm.isEmpty())throw new Exception();if(id<0)db.add(n,nm,cls);else db.update(id,n,nm);students();}catch(Exception e){Toast.makeText(this,"أدخل رقمًا واسمًا صحيحين",Toast.LENGTH_SHORT).show();}}).setNegativeButton("إلغاء",null).show();}
 void attendance(){base("الحضور والغياب","19 أسبوعًا • حصتان أسبوعيًا • "+cls);LinearLayout p=new LinearLayout(this);Button w=button("الأسبوع "+week,false),s=button("الحصة "+session,false);w.setOnClickListener(v->{week=week%19+1;attendance();});s.setOnClickListener(v->{session=session==1?2:1;attendance();});p.addView(w,new LinearLayout.LayoutParams(0,55,1));p.addView(s,new LinearLayout.LayoutParams(0,55,1));content.addView(p);content.addView(section("حالة الطلاب"));Cursor c=db.students(cls);while(c.moveToNext()){long id=c.getLong(0);String name=c.getString(2);LinearLayout r=new LinearLayout(this);r.setGravity(Gravity.CENTER_VERTICAL);r.addView(text(c.getInt(1)+" • "+name,14,false),new LinearLayout.LayoutParams(0,55,1));String[] st={"present","absent","late","unmarked"},lb={"✓ حاضر","✕ غائب","◷ متأخر","— غير مسجل"};Spinner sp=new Spinner(this);sp.setAdapter(new ArrayAdapter<String>(this,android.R.layout.simple_spinner_dropdown_item,lb));int ix=Arrays.asList(st).indexOf(db.attendance(id,week,session));sp.setSelection(ix<0?3:ix);sp.setOnItemSelectedListener(new AdapterView.OnItemSelectedListener(){public void onNothingSelected(AdapterView<?> a){}public void onItemSelected(AdapterView<?> a,View v,int pos,long z){if(pos<3)db.attendance(id,week,session,st[pos]);}});r.addView(sp,new LinearLayout.LayoutParams(145,55));content.addView(r);gap();}c.close();}
 void grades(){base("الدرجات","الفترة "+period+" • "+cls);Button per=button("التبديل إلى الفترة "+(period==1?2:1),true);per.setOnClickListener(v->{period=period==1?2:1;grades();});content.addView(per);gap();Cursor c=db.students(cls);while(c.moveToNext()){long id=c.getLong(0);String name=c.getString(2);double total=sum(db.grades(id,period));Button r=button(c.getInt(1)+" • "+name+"    "+fmt(total)+" / 100",false);r.setGravity(Gravity.RIGHT|Gravity.CENTER_VERTICAL);r.setOnClickListener(v->editGrades(id,name));content.addView(r);gap();}c.close();}
 double sum(double[]g){double x=0;for(double v:g)x+=v;return x;}String fmt(double x){return String.format(Locale.US,"%.1f",x);}
 void editGrades(long id,String name){double[]g=db.grades(id,period);String[] labels={"المشاركة / 10","الأنشطة / 10","الواجبات / 10","المشروع / 10","الاختبارات القصيرة / 20","التطبيقات العملية / 40"};double[] max={10,10,10,10,20,40};LinearLayout f=new LinearLayout(this);f.setOrientation(LinearLayout.VERTICAL);EditText[] e=new EditText[6];for(int i=0;i<6;i++){e[i]=new EditText(this);e[i].setHint(labels[i]);e[i].setInputType(2|8192);e[i].setText(fmt(g[i]));f.addView(e[i]);}new AlertDialog.Builder(this).setTitle(name+" • الفترة "+period).setView(f).setPositiveButton("حفظ",(d,w)->{try{double[]x=new double[6];for(int i=0;i<6;i++){x[i]=Double.parseDouble(e[i].getText().toString());if(x[i]<0||x[i]>max[i])throw new Exception();}db.grades(id,period,x[0],x[1],x[2],x[3],x[4],x[5]);grades();}catch(Exception z){Toast.makeText(this,"تأكد من أن الدرجات ضمن الحدود المسموحة",Toast.LENGTH_SHORT).show();}}).setNegativeButton("إلغاء",null).show();}
 void reports(){base("التقارير والإحصائيات","ملخص الفصل • "+cls);content.addView(card("إجمالي الطلاب",""+db.count(cls),NAVY));gap();content.addView(card("متوسط الفترة الأولى",fmt(db.avg(cls,1))+" / 100",BLUE));gap();content.addView(card("متوسط الفترة الثانية",fmt(db.avg(cls,2))+" / 100",GOLD));gap();content.addView(card("الحضور",db.present(cls)+" من "+db.marked(cls),GREEN));gap();TextView s=text("تصنيف الدرجات\n90–100 ممتاز\n80–89 جيد جدًا\n70–79 جيد\n60–69 مقبول\nأقل من 60 يحتاج متابعة",14,false);s.setBackground(shape(Color.WHITE,18));content.addView(s);}
}
