package com.example.studenttracker;

import android.app.*;import android.os.*;import android.graphics.*;import android.graphics.drawable.*;import android.print.*;import android.view.*;import android.widget.*;import android.database.Cursor;import java.util.*;

public class MainActivity extends Activity{
 StudentDb db; LinearLayout root,body; String cls="1م أ"; int week=1,session=1,period=1; final int NAVY=Color.rgb(11,79,108),BLUE=Color.rgb(19,119,169),BG=Color.rgb(247,249,251),TEXT=Color.rgb(31,41,55);
 @Override public void onCreate(Bundle b){super.onCreate(b);getWindow().setStatusBarColor(NAVY);getWindow().getDecorView().setLayoutDirection(View.LAYOUT_DIRECTION_RTL);db=new StudentDb(this);home();}
 TextView t(String s,int size,boolean bold){TextView v=new TextView(this);v.setText(s);v.setTextSize(size);v.setTextColor(TEXT);v.setGravity(Gravity.CENTER_VERTICAL|Gravity.RIGHT);v.setTypeface(null,bold?1:0);v.setPadding(16,10,16,10);return v;}
 GradientDrawable bg(int c,int r){GradientDrawable g=new GradientDrawable();g.setColor(c);g.setCornerRadius(r);g.setStroke(1,Color.rgb(225,230,235));return g;}
 Button b(String s,boolean primary){Button x=new Button(this);x.setText(s);x.setAllCaps(false);x.setTextSize(13);x.setTextColor(primary?Color.WHITE:NAVY);x.setBackground(bg(primary?BLUE:Color.WHITE,24));return x;}
 void base(String title){root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(BG);TextView h=t(title,21,true);h.setTextColor(Color.WHITE);h.setGravity(Gravity.CENTER);h.setBackgroundColor(NAVY);root.addView(h,new LinearLayout.LayoutParams(-1,62));ScrollView sv=new ScrollView(this);body=new LinearLayout(this);body.setOrientation(LinearLayout.VERTICAL);body.setPadding(14,14,14,30);sv.addView(body);root.addView(sv,new LinearLayout.LayoutParams(-1,0,1));setContentView(root);}
 void nav(){LinearLayout n=new LinearLayout(this);n.setPadding(8,8,8,8);String[] a={"الرئيسية","الطلاب","الحضور","الدرجات","التقارير"};for(String s:a){Button q=b(s,false);q.setOnClickListener(v->{if(s.equals("الرئيسية"))home();else if(s.equals("الطلاب"))students();else if(s.equals("الحضور"))attendance();else if(s.equals("الدرجات"))grades();else reports();});n.addView(q,new LinearLayout.LayoutParams(0,54,1));}body.addView(n);}
 void home(){base("نظام متابعة الطلاب");TextView x=t("المهارات الرقمية • 1447–1448هـ",18,true);body.addView(x);Spinner sp=new Spinner(this);sp.setAdapter(new ArrayAdapter<String>(this,android.R.layout.simple_spinner_dropdown_item,StudentDb.CLASSES));sp.setSelection(Math.max(0,Arrays.asList(StudentDb.CLASSES).indexOf(cls)));final boolean[] ready={false};sp.postDelayed(()->ready[0]=true,200);sp.setOnItemSelectedListener(new android.widget.AdapterView.OnItemSelectedListener(){public void onNothingSelected(android.widget.AdapterView a){}public void onItemSelected(android.widget.AdapterView a,View v,int p,long id){if(!ready[0])return;String selected=StudentDb.CLASSES[p];if(!selected.equals(cls)){cls=selected;home();}}});body.addView(sp);body.addView(t("عدد الطلاب: "+db.count(cls),17,true));body.addView(t("الحضور المسجل: "+db.present(cls)+" من "+db.marked(cls),16,false));body.addView(t("متوسط الفترة الأولى: "+fmt(db.avg(cls,1))+" / 100",16,false));body.addView(t("متوسط الفترة الثانية: "+fmt(db.avg(cls,2))+" / 100",16,false));nav();}
 void students(){base("إدارة الطلاب — "+cls);nav();Button add=b("＋ إضافة طالب",true);add.setOnClickListener(v->addStudent());body.addView(add);Cursor c=db.students(cls);while(c.moveToNext()){long id=c.getLong(0);String name=c.getString(2);LinearLayout row=new LinearLayout(this);row.setGravity(Gravity.CENTER_VERTICAL);TextView q=t(c.getInt(1)+" — "+name,16,false);row.addView(q,new LinearLayout.LayoutParams(0,58,1));Button del=b("حذف",false);del.setOnClickListener(v->{new AlertDialog.Builder(this).setTitle("حذف الطالب").setMessage("هل تريد حذف "+name+"؟").setPositiveButton("حذف",(d,w)->{db.delete(id);students();}).setNegativeButton("إلغاء",null).show();});row.addView(del,new LinearLayout.LayoutParams(90,54));body.addView(row);body.addView(t("────────────────────────",8,false));}c.close();}
 void addStudent(){LinearLayout f=new LinearLayout(this);f.setOrientation(LinearLayout.VERTICAL);EditText no=new EditText(this);no.setHint("رقم الطالب");no.setInputType(2);EditText name=new EditText(this);name.setHint("اسم الطالب");f.addView(no);f.addView(name);new AlertDialog.Builder(this).setTitle("إضافة طالب").setView(f).setPositiveButton("حفظ",(d,w)->{try{db.add(Integer.parseInt(no.getText().toString()),name.getText().toString(),cls);students();}catch(Exception e){Toast.makeText(this,"أدخل الرقم والاسم",Toast.LENGTH_SHORT).show();}}).setNegativeButton("إلغاء",null).show();}
 void attendance(){base("الحضور والغياب — "+cls);nav();LinearLayout pick=new LinearLayout(this);Button pw=b("الأسبوع: "+week,false);Button ps=b("الحصة: "+session,false);pw.setOnClickListener(v->{week=week%19+1;attendance();});ps.setOnClickListener(v->{session=session==1?2:1;attendance();});pick.addView(pw,new LinearLayout.LayoutParams(0,54,1));pick.addView(ps,new LinearLayout.LayoutParams(0,54,1));body.addView(pick);Cursor c=db.students(cls);while(c.moveToNext()){long id=c.getLong(0);String name=c.getString(2);LinearLayout r=new LinearLayout(this);TextView n=t(c.getInt(1)+" — "+name,15,false);r.addView(n,new LinearLayout.LayoutParams(0,58,1));String[] states={"present","absent","late","unmarked"};String[] labels={"✓ حاضر","✕ غائب","م متأخر","— غير مسجل"};Spinner s=new Spinner(this);s.setAdapter(new ArrayAdapter<String>(this,android.R.layout.simple_spinner_dropdown_item,labels));String old=db.attendance(id,week,session);int ix=Arrays.asList(states).indexOf(old);s.setSelection(ix<0?3:ix);s.setOnItemSelectedListener(new android.widget.AdapterView.OnItemSelectedListener(){public void onNothingSelected(android.widget.AdapterView a){}public void onItemSelected(android.widget.AdapterView a,View v,int p,long z){if(p<3)db.attendance(id,week,session,states[p]);}});r.addView(s,new LinearLayout.LayoutParams(145,58));body.addView(r);}c.close();}
 void grades(){base("الدرجات — "+cls);nav();Button per=b("الفترة: "+period,false);per.setOnClickListener(v->{period=period==1?2:1;grades();});body.addView(per);Cursor c=db.students(cls);while(c.moveToNext()){long id=c.getLong(0);String name=c.getString(2);Button row=b(c.getInt(1)+" — "+name+"  •  "+fmt(sum(db.grades(id,period)))+"/100",false);row.setOnClickListener(v->editGrades(id,name));body.addView(row,new LinearLayout.LayoutParams(-1,58));}c.close();}
 double sum(double[]g){double x=0;for(double v:g)x+=v;return x;}String fmt(double x){return String.format(java.util.Locale.US,"%.1f",x);}
 void editGrades(long id,String name){double[]g=db.grades(id,period);String[] labels={"المشاركة / 10","الأنشطة / 10","الواجبات / 10","المشروع / 10","الاختبارات القصيرة / 20","التطبيقات العملية / 40"};LinearLayout f=new LinearLayout(this);f.setOrientation(LinearLayout.VERTICAL);EditText[] e=new EditText[6];for(int i=0;i<6;i++){e[i]=new EditText(this);e[i].setHint(labels[i]);e[i].setInputType(2|8192);e[i].setText(fmt(g[i]));f.addView(e[i]);}new AlertDialog.Builder(this).setTitle(name+" — الفترة "+period).setView(f).setPositiveButton("حفظ",(d,w)->{try{double[]x=new double[6];for(int i=0;i<6;i++)x[i]=Double.parseDouble(e[i].getText().toString());db.grades(id,period,x[0],x[1],x[2],x[3],x[4],x[5]);grades();}catch(Exception z){Toast.makeText(this,"تحقق من الدرجات",Toast.LENGTH_SHORT).show();}}).setNegativeButton("إلغاء",null).show();}
 void reports(){base("التقارير والإحصائيات — "+cls);nav();body.addView(t("عدد الطلاب: "+db.count(cls),17,true));body.addView(t("متوسط الفترة الأولى: "+fmt(db.avg(cls,1))+" / 100",16,false));body.addView(t("متوسط الفترة الثانية: "+fmt(db.avg(cls,2))+" / 100",16,false));body.addView(t("الحضور المسجل: "+db.present(cls)+" من "+db.marked(cls),16,false));Button p=b("طباعة التقرير / حفظ PDF",true);p.setOnClickListener(v->print());body.addView(p);body.addView(t("تصنيف الدرجات: 90–100 ممتاز • 80–89 جيد جدًا • 70–79 جيد • 60–69 مقبول • أقل من 60 يحتاج متابعة.",15,false));}
 void print(){final android.webkit.WebView w=new android.webkit.WebView(this);StringBuilder h=new StringBuilder("<html dir='rtl'><meta charset='utf-8'><style>body{font-family:sans-serif;padding:25px}table{width:100%;border-collapse:collapse}td,th{border:1px solid #888;padding:6px;text-align:center}th{background:#e9f2f7}</style><h1>تقرير متابعة الطلاب</h1><h2>الفصل "+cls+"</h2><table><tr><th>الرقم</th><th>الطالب</th><th>الفترة 1</th><th>الفترة 2</th><th>المتوسط</th></tr>");Cursor c=db.students(cls);while(c.moveToNext()){double a=sum(db.grades(c.getLong(0),1)),d=sum(db.grades(c.getLong(0),2));h.append("<tr><td>").append(c.getInt(1)).append("</td><td>").append(c.getString(2)).append("</td><td>").append(fmt(a)).append("</td><td>").append(fmt(d)).append("</td><td>").append(fmt((a+d)/2)).append("</td></tr>");}c.close();h.append("</table></html>");w.loadDataWithBaseURL(null,h.toString(),"text/html","UTF-8",null);w.setWebViewClient(new android.webkit.WebViewClient(){public void onPageFinished(android.webkit.WebView v,String u){PrintManager pm=(PrintManager)getSystemService(PRINT_SERVICE);pm.print("تقرير "+cls,v.createPrintDocumentAdapter("تقرير "+cls),new PrintAttributes.Builder().setMediaSize(PrintAttributes.MediaSize.ISO_A4).build());}});}
}
